import { describe, expect, it } from 'vitest'
import { timingLabCalibration } from './timingLabCalibration'

const calibration = {
  modelVersion: 2 as const,
  audioOffsetMs: 0,
  inputOffsetMs: 0,
  videoOffsetMs: 0,
}

describe('timingLabCalibration', () => {
  it('advances Bluetooth audio and leaves only input-device delay in scoring', () => {
    expect(
      timingLabCalibration({
        calibration,
        runInputOffsetMs: 0,
        suggestedCorrectionMs: 146,
        outputLatencySeconds: 0.128,
        inputMode: 'standard',
      }),
    ).toEqual({
      ...calibration,
      audioOffsetMs: 128,
      inputOffsetMs: 18,
      videoOffsetMs: 0,
    })
  })

  it('repairs an existing input-only preset and the bad automatic visual shift', () => {
    expect(
      timingLabCalibration({
        calibration: {
          ...calibration,
          inputOffsetMs: 146,
          videoOffsetMs: -128,
        },
        runInputOffsetMs: 146,
        suggestedCorrectionMs: 1,
        outputLatencySeconds: 0.128,
        inputMode: 'standard',
      }),
    ).toMatchObject({
      audioOffsetMs: 128,
      inputOffsetMs: 19,
      videoOffsetMs: 0,
    })
  })

  it('uses the measured end-to-end correction when output latency is unavailable', () => {
    expect(
      timingLabCalibration({
        calibration,
        runInputOffsetMs: 0,
        suggestedCorrectionMs: 52,
        outputLatencySeconds: 0,
        inputMode: 'standard',
      }),
    ).toMatchObject({
      audioOffsetMs: 52,
      inputOffsetMs: 0,
      videoOffsetMs: 0,
    })
  })

  it('repairs an existing input-only preset when output latency is unavailable', () => {
    expect(
      timingLabCalibration({
        calibration: {
          ...calibration,
          inputOffsetMs: 146,
          videoOffsetMs: -146,
        },
        runInputOffsetMs: 146,
        suggestedCorrectionMs: 0,
        outputLatencySeconds: 0,
        inputMode: 'standard',
      }),
    ).toMatchObject({
      audioOffsetMs: 146,
      inputOffsetMs: 0,
      videoOffsetMs: 0,
    })
  })

  it('preserves a manual visual correction that was not generated by the bad route fix', () => {
    expect(
      timingLabCalibration({
        calibration: { ...calibration, videoOffsetMs: 17 },
        runInputOffsetMs: 0,
        suggestedCorrectionMs: 146,
        outputLatencySeconds: 0.128,
        inputMode: 'standard',
      }),
    ).toMatchObject({ videoOffsetMs: 17 })
  })

  it('moves the complete Tap route measurement into audio and clears synthetic input delay', () => {
    expect(
      timingLabCalibration({
        calibration: {
          ...calibration,
          audioOffsetMs: 128,
          inputOffsetMs: 18,
        },
        runInputOffsetMs: 18,
        suggestedCorrectionMs: 0,
        outputLatencySeconds: 0.128,
        inputMode: 'tap',
      }),
    ).toMatchObject({
      audioOffsetMs: 146,
      inputOffsetMs: 0,
      videoOffsetMs: 0,
    })
  })
})
