import { describe, expect, it } from 'vitest'
import { timingLabCalibration } from './timingLabCalibration'

const calibration = {
  modelVersion: 2 as const,
  audioOffsetMs: 0,
  inputOffsetMs: 0,
  videoOffsetMs: 0,
}

describe('timingLabCalibration', () => {
  it('advances Bluetooth audio without changing established input timing', () => {
    expect(
      timingLabCalibration({
        calibration,
        runInputOffsetMs: 0,
        suggestedCorrectionMs: 146,
        outputLatencySeconds: 0.128,
      }),
    ).toEqual({
      ...calibration,
      audioOffsetMs: 146,
      inputOffsetMs: 0,
      videoOffsetMs: 0,
    })
  })

  it('preserves existing input timing while repairing the bad visual shift', () => {
    expect(
      timingLabCalibration({
        calibration: {
          ...calibration,
          inputOffsetMs: 146,
          videoOffsetMs: -128,
        },
        runInputOffsetMs: 146,
        suggestedCorrectionMs: 1,
        outputLatencySeconds: 0.128,
      }),
    ).toMatchObject({
      audioOffsetMs: 1,
      inputOffsetMs: 146,
      videoOffsetMs: 0,
    })
  })

  it('uses the measured end-to-end correction when output latency is unavailable', () => {
    expect(
      timingLabCalibration({
        calibration,
        runInputOffsetMs: 0,
        suggestedCorrectionMs: 52,
        outputLatencySeconds: 0,
      }),
    ).toMatchObject({
      audioOffsetMs: 52,
      inputOffsetMs: 0,
      videoOffsetMs: 0,
    })
  })

  it('does not reinterpret input timing when output latency is unavailable', () => {
    expect(
      timingLabCalibration({
        calibration: {
          ...calibration,
          inputOffsetMs: 146,
          videoOffsetMs: -146,
        },
        runInputOffsetMs: 146,
        suggestedCorrectionMs: 0,
        outputLatencySeconds: 0,
      }),
    ).toMatchObject({
      audioOffsetMs: 0,
      inputOffsetMs: 146,
      videoOffsetMs: 0,
    })
  })

  it('preserves a manual visual correction that was not generated by the bad route fix', () => {
    expect(
      timingLabCalibration({
        calibration: { ...calibration, videoOffsetMs: 17 },
        runInputOffsetMs: 0,
        suggestedCorrectionMs: 146,
        outputLatencySeconds: 0.128,
      }),
    ).toMatchObject({ videoOffsetMs: 17 })
  })

  it('preserves a working Tap input correction when calibrating another route', () => {
    expect(
      timingLabCalibration({
        calibration: {
          ...calibration,
          audioOffsetMs: 128,
          inputOffsetMs: -25,
        },
        runInputOffsetMs: -25,
        suggestedCorrectionMs: 18,
        outputLatencySeconds: 0.128,
      }),
    ).toMatchObject({
      audioOffsetMs: 146,
      inputOffsetMs: -25,
      videoOffsetMs: 0,
    })
  })
})
